### ISSUE TITLE
Unicode hyphens

### ISSUE THREAD

**Issue by bentley** [standardebooks/manual#106]
[Unicode says:](https://www.unicode.org/versions/Unicode14.0.0/ch06.pdf)

> Because of its prevalence in legacy encodings, U+002D hyphen-minus is the most common of the dash characters used to represent a hyphen. It has ambiguous semantic value and is rendered with an average width. U+2010 hyphen represents the hyphen as found in words such as “left-to-right.” It is rendered with a narrow width. When typesetting text, U+2010 hyphen is preferred over U+002D hyphen-minus.

I have personally used U+2010 in most situations for at least a decade. In my experience, most fonts use the same glyph for U+2010 as for U+002D, but occasionally I encounter a font whose U+2010 has a better height or width because its U+002D tries to straddle hyphen and minus. Only rarely do I encounter a font with no glyph for U+2010, so another font’s glyph gets substituted instead.

Should SE start using the correct hyphen character? Typogrify already replaces U+2011 with U+002D—perhaps it should replace U+002D and U+2011 with U+2010 instead.

**Comment by acabal** [comment]
I'm not sure... if most fonts render them as the same width, then there won't be much gain except for some edge case renderers. But, it will introduce a lot of difficulty in the source code. Dashes are so common that we'd have to run typogrify much more often, and it would also become much harder to find text in the source code because we'd have to find a special dash character instead of the one on our keyboard. And it would be very non-obvious to people not familiar with the style, who are just trying to find some text in the source. They'd be surprised and confused when their search for a hyphenated word returns no results.

Plus, doing a global find and replace for such a common character in the corpus would possibly introduce a lot of errors. There's no way we can inspect and approve every single replacement by hand. But who's to say if some weird book like Tristram Shandy doesn't use hyphen-minus in some unexpected way?

Too much trouble for too little benefit I think. But, I'm open to being convinced otherwise.

**Comment by bentley** [comment]
> But who's to say if some weird book like Tristram Shandy doesn't use hyphen-minus in some unexpected way?

I strongly doubt there’s any conceivable use of hyphen‐minus (except as a minus, which is already disallowed on SE) that would become less correct by converting to hyphen. After all, it is named the hyphen‐minus.

> it would also become much harder to find text in the source code… And it would be very non-obvious to people not familiar with the style, who are just trying to find some text in the source. They'd be surprised and confused when their search for a hyphenated word returns no results.

While true, it’s just as true for en dashes, zero‐width joiners, ellipses, and curly apostrophes.

> But, it will introduce a lot of difficulty in the source code. Dashes are so common that we'd have to run typogrify much more often

Can’t argue with that.

**Comment by acabal** [comment]
@robinwhittleton @vr8hub @drgrigg @EmmaSweeney @b-t-k Any opinions on this?

**Comment by vr8hub** [comment]
All the things you said, Alex. En-dashes, zero-width joiners, ellipses, and curly apostrophes are not word-separators, and do not interfere with searching for a compound word.

If most fonts use the same glyph (wash), and some fonts don't include the U+2010 glyph (bad), then that's a pretty small set of fonts that would yield a positive result, and how many of those fonts where the glyphs are different do we think are actually used by an e-reader? 

As you said, (way) too much trouble for (way) too little benefit.

**Comment by b-t-k** [comment]
Quick thoughts...I think the search issue is the big one. A standard keyboard gives you a hyphen-minus. Searching for unicode is one of those things that slows people down, if they even figure out what they are searching for. Traditional books formed in Word, InDesign etc. all generally use a hyphen-minus (at least I believe so...I've never used anything else). Fine typography is one thing but this makes things overly complex.

If it was that important typographically I might consider adding the conversion to _build_ so the working files remained easier to manage, otherwise, as Vince paraphrased, "(way) too much trouble for (way) too little benefit."

**Comment by acabal** [comment]
OK, let's shelve this for now. Thanks for the suggestion though, I wasn't aware of U+2010!

**Comment by robinwhittleton** [comment]
One last comment: auto hyphenation would give a different hyphen to the rest of the manually hyphenated words (assuming renderers don’t use u2010 by default). You can use `hyphenate-character` to define a specific character to soft-hyphenate with (https://developer.mozilla.org/en-US/docs/Web/CSS/hyphenate-character) but no idea about reader support.
