### ISSUE TITLE
could the manual itself be offered as ePub?

### ISSUE THREAD

**Issue by ousia** [standardebooks/manual#160]
@standardebooks, many thanks for your high quality editions.

I would like to contribute some minor corrections (or improvements), discussing them first.

But I would like to read the whole manual first (or at least to page through it).

I think it would be extremely helpful for newcomers to offer the manual itself as ebook.

Many thanks for your excellent work.

**Comment by acabal** [comment]
Hi there, thanks for the suggestion. Right now we don't have plans to do that because the manual is written in RST, so we would have to maintain two branches of the manual to support an epub version. Most people who would use the manual are developing on desktops or laptops where they can easily access the full web version, so an epub version isn't going to be a priority right now.

**Comment by ousia** [comment]
@acabal, many thanks for your ultra-fast reply.

So, you use the XHTML files as sources for your ePubs.

Many thanks for making that clear.
