### ISSUE TITLE
Proposal: <dfn> for newly‐used English words

### ISSUE THREAD

**Issue by bentley** [standardebooks/manual#53]
HTML has [the `<dfn>` element](https://www.w3.org/TR/html52/textlevel-semantics.html#the-dfn-element), which “represents the defining instance of a term.” Semantically, it at least partly overlaps with [section 8.2.10 of the manual](https://standardebooks.org/manual/1.5.0/8-typography#8.2.10). Perhaps it would be appropriate to mention it there.

I said “<em>partly</em> overlaps” because I’m not sure how broad a “defining instance” is. For instance, the first example in the manual seems like a clear match: “English whalers have given this the name ‘ice blink.’” But is the second? It doesn’t contain a definition per se: “The soil consisted of that igneous gravel called <i>tuff</i>.” On the other hand, maybe “igneous gravel” counts.

Another wrinkle is style. By default, `<dfn>` is rendered in italics. The manual says to use italics for technical terms. If `<dfn>` is used for quoted English, though, it would need an additional style (maybe a class?) to un‐italicize.

```html
<p>English whalers have given this the name “<dfn class="common-english">ice blink</dfn>.”</p>
<p>The soil consisted of that igneous gravel called <dfn>tuff</dfn>.</p>
```

**Comment by acabal** [comment]
I think the problem here is exactly what you describe, which is that it would be very difficult to decide if we're really "defining a term" in running prose. It's not always clear in a running prose context that a phrase or word is really being defined, and we'd get a lot of questions about that without the ability to give clear answers.

Generally when it comes to semantic enrichment, the idea is to use semantics when a tag is already required somewhere. For example if we have to italicize something, that will require `<i>` so we may as well give it semantics while we're at it. Doing more than that is optional, because one can really go down a rabbit hole of how much semantics to add. Look up TEI for example. With TEI we could go so far as to mark up every noun in a sentence, every prepostional phrase, every personal name, etc., but doing that is an oppressive amount of work for questionable benefit.
